baseURL = "https://roi-mythology.netlify.com"
copyright = "© 2019 <a href='https://greekmythology.com'>Greek Mythology</a>. Made by <a href='https://roipeker.com'>@roipeker</a>."
description = "Reference site for greek mythology and a personal blog."
enableEmoji = true
languageCode = "en-us"
theme = "hugo-theme-basic"
title = "Greek mythology"
[[params.menu]]
name = "all"
url = "post/"
[[params.menu]]
name = "series"
url = "series/"
[[params.menu]]
name = "mitos"
url = "myths/"
[[params.menu]]
name = "about"
url = "about/"
[taxonomies]
category = "myths"
series = "series"
tag = "tags"

[outputs]
  home = ["json","html"]
  page = ["html"]
  section = ["html"]